"""empty message

Revision ID: 394cdc7f94d8
Revises: 9df06aa9ecac
Create Date: 2021-06-22 01:25:01.044509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394cdc7f94d8'
down_revision = '9df06aa9ecac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_created_on', table_name='question')
    op.drop_table('question')
    op.drop_index('ix_my_upload_created_on', table_name='my_upload')
    op.drop_table('my_upload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_upload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('imgtype', sa.VARCHAR(length=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_my_upload_created_on', 'my_upload', ['created_on'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('prediction', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_created_on', 'question', ['created_on'], unique=False)
    # ### end Alembic commands ###
